### PR TITLE
Render critical points as pyramids

### PR DESCRIPTION
**Pull request by octfx**
This pr changes the rendering type of critical points from points to pyramids.  
The pyramid apex starts out from earths center, the bases center corresponds to the location of the critical point.

### CODE REVIEW

**Comment by Flatken** [comment]
Please have a look to the minimum and maximum persistence value for the scaling. If i go to a timestep in the CinemaDB with high persistence values the rendering of pyramids get very large

**Comment by Flatken** [comment]
I do have some flickering artefacts on the pyramids. Looks like the normals or sun positions change a lot every frame

**Review by Flatken — CHANGES_REQUESTED** [review]
See general comments

**Comment by octfx** [comment]
> Please have a look to the minimum and maximum persistence value for the scaling. If i go to a timestep in the CinemaDB with high persistence values the rendering of pyramids get very large

Addressed in b0d29e39c76eb25e51e711f86c4ff5d10c9ac52a

**Comment by octfx** [comment]
> I do have some flickering artefacts on the pyramids. Looks like the normals or sun positions change a lot every frame

I could not reproduce this behavior on a Nvidia GTX1050

**Pull request merged**
